### ISSUE TITLE
Add rule capabilities to YARD

### ISSUE THREAD

**Issue by Rikkola** [kiegroup/akrivis#23]
More of a YARD ticket, but let's track it here.

To be able to make decisions based on lists of data or to return one or multiple maps as one or multiple different form of maps, the current YARD functionality is not enough.

As a solution to this I propose adding a rule element and input import types Map and List.
Rule element will start with simple goal of returning a Map or a List. A Ticket or a Person object for example would be a Map, List of Tickets is a List of Maps and then of course there can be a Map of Maps of Maps and so on.

Conditional elements will include simple rule setup. To filter collections or change the form.

```
specVersion: alpha
kind: YaRD
name: 'Merge'
inputs:
  - name: Jira 1
    type: List
  - name: Jira 2
    type: List
elements:
  - name: Merged data from two ticket streams
    type: Decision
    logic:
      type: Rules
      rules:
        - when:
            - given: $ticket
              from: Jira 1
              having:
                - status == "Blocking"
          then:
            list:
              - add: $ticket
        - when:
            given: $ticket
            from: Jira 1
            having:
              - status == "Blocking"
          then:
            list:
              - add: $ticket
```

As well as grouping functionality with the same approach. Making the YAML format act as a DSL for the RuleUnit DSL.
